### ISSUE TITLE
Version 10.2 

### ISSUE THREAD

**Issue by Lalithaynlv** [dseisun/tableau_admin#11]
Unable to implement the tmcmd in Unix using this script 
error encountered :

 ./tabcmd.sh login --server http://192.168.8.162:8040 --username emarsys
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/tableausoftware/tabcmd/Tabcmd : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

Can you please help to resolve this , its urgent as we are unable to move forward due to this .
ps : we are using 10.2 version only tried for only 10.0 also not working .
Java version am using :
[~]$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
[~]$ javac -version
javac 1.6.0_45
~]$ uname -a
Linux ENT-DV-UHBAT02 2.6.18-419.el5 #1 SMP Wed Feb 22 22:40:57 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

Can you please let me know if 9.3 version would work (tabcmd).

**Comment by takuni** [comment]
http://javarevisited.blogspot.jp/2015/05/fixing-unsupported-majorminor-version.html
